# -*- encoding: utf-8 -*-
#
=begin
#giphy-api

#Giphy's public api.

OpenAPI spec version: 0.9.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

$:.push File.expand_path("../lib", __FILE__)
require "GiphyClient/version"

Gem::Specification.new do |s|
  s.name        = "GiphyClient"
  s.version     = GiphyClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Swagger-Codegen"]
  s.email       = [""]
  s.homepage    = "https://github.com/Giphy/giphy-ruby-client"
  s.summary     = "Networking client for the Giphy API."
  s.description = "Giphy's public api."
  s.license     = "MPLv2"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus'

  s.add_development_dependency 'rspec'
  s.add_development_dependency 'vcr'
  s.add_development_dependency 'webmock'

  s.files         = `find *`.split("\n").uniq.sort.select{|f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
